:scheduler:
  :schedule:
    crawl_scheduled_sources:
      cron: "0 */2 * * *"
      class: "CrawlSourceJob"
      queue: "default"

    delete_pending_rejected_sources:
      cron: "0 0 1 * *"
      class: "DeletePendingRejectedSourcesJob"
      queue: "default"

    refresh_email_suggestion:
      cron: "0 4 * * *"
      class: "RefreshEmailSuggestionJob"
      queue: "default"

    refresh_sale_suggestion:
      cron: "*/15 * * * *"
      class: "RefreshSaleSuggestionJob"
      queue: "default"
